/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.github.giorgioazzinnaro.keycloak_x509_envoy

class Library {
    fun someLibraryMethod(): Boolean {
        return true
    }
}
